Vagrant.configure("2") do |config|
  config.vm.define "websrv" do |web|
    web.vm.box = "bento/ubuntu-16.04"
    web.vm.hostname = 'websrv'

    web.vm.network :private_network, ip: "10.20.30.100"

    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "websrv"]
    end

    web.vm.synced_folder "src", "/src"

  end

  config.vm.define "elasticsrv" do |elastic|
    elastic.vm.box = "bento/ubuntu-16.04"
    elastic.vm.hostname = 'elasticsrv'

    elastic.vm.network :private_network, ip: "192.168.56.102"

    elastic.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "elasticsrv"]
    end
  end

  config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "playbook.yml"
  end

end
