    - apt_repository:
         repo: 'ppa:ondrej/php'
         update_cache: yes

    - apt:
         name: php7.1
         update_cache: yes
    - apt:
         name: php7.1-fpm
         update_cache: yes

    - name: main | uninstall apache packages
      apt: >
        pkg={{ item }}
        state=absent
        purge=yes
        force=yes
      with_items:
        - apache2*